<template>
    <!-- Generated by IcoMoon.io -->
    <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        viewBox="0 0 32 32"
    >
        <title>logo</title>
        <path
            fill="none"
            stroke="#1b2d45"
            stroke-width="2.8444"
            stroke-miterlimit="3"
            stroke-linecap="round"
            stroke-linejoin="miter"
            d="M24.718 21.547l1.934-1.934M5.035 12.786l4.139-4.124M12.715 4.964v0.142M19.541 26.724l-0.085-0.057M5.205 19.726l0.028-0.028M7.979 24.050l3.94-3.925M9.074 15.858l10.567-10.581M12.388 26.752l14.293-14.293M15.758 16.284l8.22-8.22"
        ></path>
    </svg>
</template>
